### PR TITLE
Simplify no wstreambuf support.

### PR DESCRIPTION
**Pull request by jzmaddock**
See https://github.com/boostorg/serialization/pull/224.

### CODE REVIEW

**Comment by jzmaddock** [comment]
@robertramey : Looks like the CI is stalled indefinitely waiting for a runner - that's because the ubuntu-18 image has been deprecated (for example) and available runners are stupidly scarce.  Shall I update the images used as part of this PR?  The catch is that older gcc versions will no longer be available.  They *are* available with the drone CI runners that the cpp alliance provides for us though...

**Comment by robertramey** [comment]
Don’t worry about it. Boost I never really works for me anyway. I’ll except the PR, sync, my own machine, and run the tests locally. I’m sure this will be fine with a change this modest. Many thanks to you both for your help on these very Obscure issues. Robert Rameywww.rrsd.comOn Apr 30, 2023, at 1:15 AM, jzmaddock ***@***.***> wrote:﻿
@robertramey : Looks like the CI is stalled indefinitely waiting for a runner - that's because the ubuntu-18 image has been deprecated (for example) and available runners are stupidly scarce.  Shall I update the images used as part of this PR?  The catch is that older gcc versions will no longer be available.  They are available with the drone CI runners that the cpp alliance provides for us though...

**Comment by jzmaddock** [comment]
@robertramey, I added the requirement to all of the tests which had linker errors when building the tests with -DBOOST_NO_STD_LOCALE.  Basically anything which used the xml_archives anywhere.

**Comment by ArielSilver** [comment]
pull request created

**Pull request merged**
