### PR TITLE
Fix undefined reference to codecvt_null<wchar_t>

### PR DESCRIPTION
**Pull request by xantares**
See https://svn.boost.org/trac/boost/ticket/12205

### CODE REVIEW

**Comment by sav-ix** [comment]
Hi.
Patch work only for **Release+shared** builds. It doesn't fix build error for **Debug+shared** builds.
Tested using Mingw-w64.

**Comment by xantares** [comment]
@sav-ix, indeded, I also get undefined refs to singleton_module::is_locked() when linking libboost_serialization-mt-d.dll.a in debug mode, nothing indicates it's related though.

**Comment by starius** [comment]
Fails for me with the following error:

```
bin.v2/libs/serialization/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/target-os-windows/threadapi-win32/
threading-multi/xml_wiarchive.o:xml_wiarchive.cpp:(.rdata$.refptr._ZTVN5boost7archive6detail18utf8_codecvt_facet
E[.refptr._ZTVN5boost7archive6detail18utf8_codecvt_facetE]+0x0): undefined reference to `vtable for boost::archi
ve::detail::utf8_codecvt_facet'
collect2: error: ld returned 1 exit status
    "x86_64-w64-mingw32.shared-g++"   "-Wl,--out-implib,bin.v2/libs/serialization/build/gcc-mingw-mxe/release/ab
i-ms/binary-format-pe/target-os-windows/threadapi-win32/threading-multi/libboost_wserialization-mt.dll.a" -o "bi
n.v2/libs/serialization/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/target-os-windows/threadapi-win32/th
reading-multi/libboost_wserialization-mt.dll" -Wl,-h -Wl,libboost_wserialization-mt.dll -shared -Wl,--start-grou
p "bin.v2/libs/serialization/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/target-os-windows/threadapi-win
32/threading-multi/basic_text_wiprimitive.o" "bin.v2/libs/serialization/build/gcc-mingw-mxe/release/abi-ms/binar
y-format-pe/target-os-windows/threadapi-win32/threading-multi/basic_text_woprimitive.o" "bin.v2/libs/serializati
on/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/target-os-windows/threadapi-win32/threading-multi/text_wi
archive.o" "bin.v2/libs/serialization/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/target-os-windows/thre
adapi-win32/threading-multi/text_woarchive.o" "bin.v2/libs/serialization/build/gcc-mingw-mxe/release/abi-ms/bina
ry-format-pe/target-os-windows/threadapi-win32/threading-multi/xml_wgrammar.o" "bin.v2/libs/serialization/build/
gcc-mingw-mxe/release/abi-ms/binary-format-pe/target-os-windows/threadapi-win32/threading-multi/xml_wiarchive.o"
 "bin.v2/libs/serialization/build/gcc-mingw-mxe/release/abi-ms/binary-format-pe/target-os-windows/threadapi-win3
2/threading-multi/xml_woarchive.o" "bin.v2/libs/serialization/build/gcc-mingw-mxe/release/abi-ms/binary-format-p
e/target-os-windows/threadapi-win32/threading-multi/codecvt_null.o" "bin.v2/libs/serialization/build/gcc-mingw-m
xe/release/abi-ms/binary-format-pe/target-os-windows/threadapi-win32/threading-multi/libboost_serialization-mt.d
ll.a"  -Wl,-Bstatic  -Wl,-Bdynamic  -Wl,--end-group -mthreads -m64
```

I am trying to update boost from 1.60 to 1.62 in [MXE](http://mxe.cc).
Bug in MXE: https://github.com/mxe/mxe/pull/1549

**Comment by xantares** [comment]
@starius I use this patch for 1.62 too, it works provided that you compile in release mode

**Comment by starius** [comment]
I also build in release mode (variant=release), but get an error.
Whole build command: https://git.io/vPx7a

How does release/debug mode affect the failure?

**Comment by xantares** [comment]
@starius, A wild guess is that in release mode the compiler tries to optimize more aggressively and inline symbols get optimized away.
In archlinux we use gcc 6.2, with these ```cxxflags="-std=c++11 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4"```

**Comment by starius** [comment]
If it is true, then it is not a real fix, but a workaround. What is a real
reason of the failure and how to solve it?

25 окт. 2016 г. 9:58 пользователь "xantares" <notifications@github.com>
написал:

**Comment by xantares** [comment]
: ) if only I knew

**Comment by Frederick888** [comment]
I'm building from Debian and I have exactly the same issue as @starius . Any updates?

**Comment by xantares** [comment]
nope, patch is still needed with boost 1.63

**Comment by Frederick888** [comment]
@xantares I meant my compilation failed for the same reason. But I found that I could build with your patch using `link=static`.

**Comment by xantares** [comment]
are you sure you need to patch when disabling shared libs ?

**Comment by Frederick888** [comment]
@xantares No. I'm rushing to build a bunch of apps and didn't have time to carefully check each of them.

**Comment by starius** [comment]
It failed for me only for shared targets. Static worked well.

But the patch didn't help. I have updated gcc and mingw and have not retested if the patch works.

**Comment by sav-ix** [comment]
Hello, Robert,
Does closing this issue mean
- it already fixed,
OR
- it won't be fixed?

Thank you.

**Comment by robertramey** [comment]
it means I'm pretty sure it's fixed.  I've checked it into the develop branch.  Merge to master still pending.  I passes on my machine and most of the machines in the Boost test matrix.  I've still got failures there but I don't think they are related to this.

**Comment by xantares** [comment]
what commit fixed it ?

**Comment by robertramey** [comment]
I don't remember it was some time ago - but no tests are failing due to this:

http://www.boost.org/development/tests/master/developer/serialization.html

**Comment by sav-ix** [comment]
Just tested [Boost-1.65.0_beta1_rc2](https://dl.bintray.com/boostorg/beta/1.65.0.beta.1/source/) build using mingw-w64 with <Debug|Release> Shared configurations and error reproduced in both cases.
Robert, could you re-open this ticket, since error still persist?

**Comment by rwols** [comment]
Pretty off-topic, I don't know where else to put this, but why is there no issues page?

**Comment by xantares** [comment]
@robertramey the issue is still present in boost 1.65 beta 1 rc2 that includes your latest commit, could you reopen ?

**Comment by sav-ix** [comment]
Error not reproduced after moving to 1.66.0. Tested for builds using mingw-w64 with <Debug|Release> Shared configurations. Thank you for fix, Robert!

**Comment by xantares** [comment]
Same here, thanks @robertramey.

**Pull request closed without merging**
