### PR TITLE
Fix applying offset to null pointer

### LINKED ISSUE #193: Clang 10 UBSan: boost/archive/iterators/escape.hpp:85:12: runtime error: applying non-zero offset 1 to null pointer
Hello,

Following code

```cpp
#include <boost/archive/iterators/ostream_iterator.hpp>
#include <boost/archive/iterators/xml_escape.hpp>

#include <iostream>
#include <string>

int main()
{
  const std::string s = "test";

  std::copy(boost::archive::iterators::xml_escape<const char*>(s.c_str()),
            boost::archive::iterators::xml_escape<const char*>(s.c_str() + s.size()),
            boost::archive::iterators::ostream_iterator<char>(std::cout));
}
```

when compiled with Clang 10 with UBSan:

> $ clang++ -o boostarchive boostarchive.cpp -fsanitize=undefined 
> $ UBSAN_OPTIONS="print_stacktrace=1" ./boostarchive

produces the following error:

```
boost/archive/iterators/escape.hpp:85:12: runtime error: applying non-zero offset 1 to null pointer
    #0 0x42be87 in boost::archive::iterators::escape<boost::archive::iterators::xml_escape<char const*>, char const*>::increment() (boostarchive+0x42be87)
    #1 0x42bd01 in void boost::iterators::iterator_core_access::increment<boost::archive::iterators::xml_escape<char const*> >(boost::archive::iterators::xml_escape<char const*>&) (boostarchive+0x42bd01)
    #2 0x42a724 in boost::iterators::detail::iterator_facade_base<boost::archive::iterators::xml_escape<char const*>, char, boost::iterators::single_pass_traversal_tag, char, long, false, false>::operator++() (boostarchive+0x42a724)
    #3 0x42a1da in boost::archive::iterators::ostream_iterator<char> std::__copy_move<false, false, std::input_iterator_tag>::__copy_m<boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::ostream_iterator<char> >(boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::ostream_iterator<char>) (boostarchive+0x42a1da)
    #4 0x429d9f in boost::archive::iterators::ostream_iterator<char> std::__copy_move_a<false, boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::ostream_iterator<char> >(boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::ostream_iterator<char>) (boostarchive+0x429d9f)
    #5 0x4298aa in boost::archive::iterators::ostream_iterator<char> std::__copy_move_a2<false, boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::ostream_iterator<char> >(boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::ostream_iterator<char>) (boostarchive+0x4298aa)
    #6 0x42946b in boost::archive::iterators::ostream_iterator<char> std::copy<boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::ostream_iterator<char> >(boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::xml_escape<char const*>, boost::archive::iterators::ostream_iterator<char>) (boostarchive+0x42946b)
    #7 0x4292a9 in main (boostarchive+0x4292a9)
    #8 0x3cdc61ed1c in __libc_start_main (/lib64/libc.so.6+0x3cdc61ed1c)
    #9 0x403434 in _start (boostarchive+0x403434)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior boost/archive/iterators/escape.hpp:85:12 in
test
```

### PR DESCRIPTION
**Pull request by ostash**
This should fix #193.

### CODE REVIEW

**Comment by ostash** [comment]
@robertramey - what do you think? Can this be merged?

**Comment by robertramey** [comment]
Above it says "All checks have failed".  Why do you think this should be merged?

**Comment by ostash** [comment]
I will fix checks, but for now, I'd like hear feedback whether this approach looks ok :)

**Comment by hajokirchhoff** [comment]
Since m_bnext get's initialized to NULL in the constructor, perhaps
`if (m_bnext != NULL && ++m_bnext<m_bend) {` would be acceptable?

**Pull request closed without merging**
